// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var Path;
  Path = require('path');
  exports.isPartial = function (path) {
    return /^_/.test(Path.basename(path));
  };
  exports.isAbsolutePath = function (path) {
    return new RegExp('^' + Path.sep).test(path);
  };
}.call(this);
