// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var isPartial, isString, Path, removeBasePath, removeMustacheExtension, removeUnderscore;
  Path = require('path');
  isString = require('minutils').isString;
  isPartial = require('./file_utils').isPartial;
  module.exports = function (path, options) {
    var baseDir, cache$, fp, friendlyPath;
    if (null == options)
      options = {};
    cache$ = options;
    friendlyPath = cache$.friendlyPath;
    baseDir = cache$.baseDir;
    if (isString(friendlyPath))
      return friendlyPath;
    fp = removeMustacheExtension(path);
    if (isString(baseDir) && baseDir !== path)
      fp = removeBasePath(baseDir, fp);
    if (isPartial(fp))
      fp = removeUnderscore(fp);
    if ('function' === typeof friendlyPath)
      fp = friendlyPath(fp, path);
    return fp;
  };
  removeBasePath = function (baseDir, path) {
    return path.replace(new RegExp('^' + baseDir + Path.sep), '');
  };
  removeMustacheExtension = function (path) {
    return path.replace(/\.mustache$/, '');
  };
  removeUnderscore = function (path) {
    var base, filename;
    filename = Path.basename(path);
    base = filename.replace(/^_/, '');
    return path.replace(new RegExp('' + filename + '$'), base);
  };
}.call(this);
