// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var fs, getNodeVersion, getTemplate, getTemplates, glob, isAbsolutePath, Path, readFileSync;
  fs = require('fs');
  glob = require('glob');
  Path = require('path');
  isAbsolutePath = require('./file_utils').isAbsolutePath;
  getTemplates = function (basePath) {
    return glob.sync(Path.normalize('' + basePath + '/**/*.mustache')).map(getTemplate);
  };
  getTemplate = function (path) {
    if (!isAbsolutePath(path))
      throw new Error('Path argument must be an absolute path');
    if (!fs.existsSync(path))
      throw new Error('' + path + ' does not exist');
    return {
      path: path,
      contents: readFileSync(path)
    };
  };
  getNodeVersion = function () {
    return +process.version.slice(1).split('.')[1];
  };
  readFileSync = function (path) {
    var options;
    options = getNodeVersion() < 10 ? 'utf8' : { encoding: 'utf8' };
    return fs.readFileSync(path, options);
  };
  module.exports = {
    getTemplates: getTemplates,
    getTemplate: getTemplate
  };
}.call(this);
