// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var cache$, fs, getFriendlyPath, getTemplate, getTemplates, isPartial, partition;
  fs = require('fs');
  partition = require('minutils').partition;
  isPartial = require('./file_utils').isPartial;
  cache$ = require('./get_templates');
  getTemplates = cache$.getTemplates;
  getTemplate = cache$.getTemplate;
  getFriendlyPath = require('./get_friendly_path');
  module.exports = function (baseDir, options) {
    var cache$1, object, partials, result, template, templates;
    if (null == options)
      options = {};
    options = {
      baseDir: baseDir,
      friendlyPath: options.friendlyPath
    };
    if (fs.statSync(baseDir).isFile()) {
      result = {
        partials: [],
        templates: []
      };
      template = getTemplate(baseDir);
      template.friendlyPath = getFriendlyPath(baseDir, options);
      (isPartial(template.path) ? result.partials : result.templates).push(template);
      return result;
    } else {
      cache$1 = partition(getTemplates(baseDir), function (template) {
        return isPartial(template.path);
      });
      partials = cache$1[0];
      templates = cache$1[1];
      for (var cache$2 = [
            partials,
            templates
          ], i$ = 0, length$ = cache$2.length; i$ < length$; ++i$) {
        object = cache$2[i$];
        object.forEach(function (template) {
          return template.friendlyPath = getFriendlyPath(template.path, options);
        });
      }
      return {
        partials: partials,
        templates: templates
      };
    }
  };
}.call(this);
